version: '3.9'

name: nestjs_starter

services:
  valkey:
    container_name: nestjs_starter_valkey
    image: valkey/valkey:8-alpine
    ports:
      - 6379:6379

  postgres:
    container_name: nestjs_starter_postgres
    image: postgres:17-alpine
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_starter
    ports:
      - 5432:5432
